[phases.setup]
nixPkgs = ['flutter', 'python3']
nixpkgsArchive = '50ab793786d9de88ee30ec4e4c24fb4236fc2674'

[phases.install]
cmds = ['rm -f pubspec.lock', 'touch .env', 'flutter config --no-analytics', 'flutter pub get']

[phases.build]
cmds = ['flutter build web']

[start]
cmd = 'python3 -m http.server $PORT --directory build/web'

[variables]
CI = "true"
